name: Backend CI

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-backend:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: hango-backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build
        # Thêm cờ -DskipTests vào đây để bỏ qua việc quét context test khi build trên CI
        run: mvn clean verify -DskipTests