name: Frontend CI

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-frontend:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: hango-frontend

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.0'

      - run: flutter pub get

      - run: flutter analyze

      - run: flutter test